site_name: csuc-workshop
site_url: https://github.com/liatrio/csuc-workshop
repo_url: https://github.com/liatrio/csuc-workshop
edit_uri: edit/main/docs

theme:
  name: material
  logo: img/liatriologo-white.png
  favicon: img/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    ## Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    ## Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    ## Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - neoteroi.spantable
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - toc:
      permalink: true
      title: On This Page

#plugins:
#  - search
#  ## Use to auto generate nav and sidebars.
#  #- awesome-pages

extra:
  generator: false

# See https://squidfunk.github.io/mkdocs-material/customization/ for
# customization instructions
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-spantable.css

# If using awesome-pages plugin, remove this section and use .pages file.
nav:
  - 'csuc-workshop': 'index.md'
